#!/usr/bin/env python3

import os
import re


def match(line, output, in_config):
    end = re.search("};$", line)
    parameter = re.search(
        '{"([a-zA-Z_-]+)", *ConfigValue *{"(.*)"}},( *\/\/ *(.*))?',
        line)

    if in_config and end:
        return False
    elif in_config and parameter:
        if parameter.group(4) is None:
            output.write("{} = {}\n".format(
                parameter.group(1), parameter.group(2)))
        else:
            output.write("{} = {}  # {}\n".format(
                parameter.group(1), parameter.group(2), parameter.group(4)))
        return True
    elif "config_default" in line:
        return True
    return False


if __name__ == "__main__":
    basep = os.path.dirname(os.path.realpath(__file__))

    with open(basep + "/../rasseiver/src/config.hpp", "r") as config_file, \
         open(basep + "/../rasseiver/examples/minimal-config", "r") as base, \
         open(basep + "/../rasseiver/examples/default-config", "w") as output:
        output.write(
            "# This file is automatically generated by " + \
            os.path.basename(__file__) + "\n" + \
            "# Do not edit, or your changes will be overwritten\n\n" + \
            "# Minimal configuration\n" + base.read() + "\n" + \
            "# Default configuration\n")

        in_config = False
        for line in config_file.readlines():
            in_config = match(line, output, in_config)
